### ISSUE TITLE
https://borg.bauerj.eu not working anymore!?

### ISSUE THREAD

**Issue by theChaosCoder** [bauerj/borg-binaries#6]
The strange thing is I can't even ping this url. Other sites report a 502 Bad Gateway.

https://www.ssllabs.com/ssltest/analyze.html?d=borg.bauerj.eu  (scroll to very bottom)

**Comment by bauerj** [comment]
Sorry about that, there are server issues right now.  I hope to fix that in the next few hours.

**Comment by bauerj** [comment]
It should be working again.

**Comment by theChaosCoder** [comment]
I still can't connect, but it works via a webproxy site. So it is in my end this time.

**Comment by bauerj** [comment]
Yes, there were DNS issues so you might have old records cached.

**Comment by theChaosCoder** [comment]
before I close this: Will there be a borg ARM 1.1.0 final version available soon?

**Comment by bauerj** [comment]
I hope so. The build process is currently running. If I don't have to adapt the build script to changes in 1.1 it should be finished in about 4-5 hours.
